force-app/reservation-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/reservation-app/main/default/objects/Reservation__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/reservation-app/main/default/objects/Reservation__c/fields/Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_Time__c</fullName>
    <label>Date and Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/reservation-app/main/default/objects/Reservation__c/fields/Deposit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Deposit Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/reservation-app/main/default/objects/Reservation__c/fields/Preferences__c.field-meta.xml
<CustomField>
    <fullName>Preferences__c</fullName>
    <label>Preferences</label>
    <type>TextArea</type>
</CustomField>

force-app/reservation-app/main/default/objects/Reservation__c/fields/VIP__c.field-meta.xml
<CustomField>
    <fullName>VIP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VIP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/reservation-app/main/default/classes/IntegrationTest.cls
@isTest
public class IntegrationTest {
    @isTest
    public static void runHappyPath(){
        Test.setMock(HttpCalloutMock.class, new ChatGPTMockCallout());
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName = 'Contact';
        insert c;
        
        Reservation__c r = new Reservation__c();
        r.Date_and_Time__c = System.now().addDays(5);
        r.Preferences__c = 'Test Preferences';
        r.Deposit_Amount__c = 500;
        r.Customer__c = c.Id;
        
        Test.startTest();
        insert r;
        Test.stopTest();
        
        r = [SELECT Id, VIP__c FROM Reservation__c LIMIT 1];
        Assert.isTrue(r.VIP__c, 'reservation should be VIP');
        List<Task> tasks = [SELECT Id, WhatId, Subject, Description FROM Task];
        Assert.areEqual(2, tasks.size(), 'Should be 2 tasks created');
        Assert.areEqual('Remind customer about reservation.', tasks[0].Description, 'Reminder task description wrong');
        Assert.areEqual('Test Content', tasks[1].Description, 'Special VIP task description wrong');
    }
    
    public class ChatGPTMockCallout implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {            
            String response = '{"choices": ['+
                '{' +
                  '"finish_reason": "stop",' +
                  '"index": 0,' +
                  '"message": {' +
                    '"content": "Test Content",' +
                    '"role": "assistant"' +
                  '}' +
                '}' +
              '],' +
              '"created": 1677823794,' +
              '"id": "chatcmpl-6psu2Yl4ZFP5wb1S2CK9bCu7r2fEz",' +
              '"model": "gpt-3.5-turbo-0301",' +
              '"object": "chat.completion",' +
              '"usage": {' +
                '"completion_tokens": 29,' +
                '"prompt_tokens": 54,' +
                '"total_tokens": 83' +
              '}' +
            '}';
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(response);
            res.setStatusCode(200);
            return res;
        }
    }
}